agence.id=AGENCE2
agence.password=secret2
agence.name=Agence Tourisme Go
server.port=9002
hotel1.base-url=http://localhost:8081/hotelservice/api
hotel2.base-url=http://localhost:8082/hotelservice/api
