agence.id=AGENCE1
agence.password=secret1
agence.name=Agence Voyages Simples
server.port=9001
hotel1.base-url=http://localhost:8081/hotelservice/api
hotel2.base-url=http://localhost:8082/hotelservice/api
