

server.port=8081

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:hotel1db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true


hotel.name=Hotel Paradise
hotel.stars=4
hotel.ville=Paris
hotel.pays=France
hotel.rue=Champs Elysees
hotel.numero=10
hotel.latitude=48.870
hotel.longitude=2.305
hotel.code=H1
