

server.port=8082

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:hotel2db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true


hotel.name=Hotel Sunny Beach
hotel.stars=3
hotel.ville=Montpellier
hotel.pays=France
hotel.rue=Rue du Soleil
hotel.numero=5
hotel.latitude=43.600
hotel.longitude=3.900
hotel.code=H2
hotel.image-url=http://localhost:8082/images/room2.jpg
